# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth/auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/auth/auth.proto\"\x0f\n\rEmptyResponse\"!\n\x10VerifyJWTRequest\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"k\n\x13RegistrationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"%\n\x14RegistrationResponse\x12\r\n\x05token\x18\x01 \x01(\t\"&\n\x15\x46orgotPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"R\n\x15\x43hangePasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0cold_password\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t2\x99\x02\n\x0e\x41uthentication\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12.\n\tVerifyJWT\x12\x11.VerifyJWTRequest\x1a\x0e.EmptyResponse\x12;\n\x0cRegistration\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponse\x12\x38\n\x0e\x46orgotPassword\x12\x16.ForgotPasswordRequest\x1a\x0e.EmptyResponse\x12\x38\n\x0e\x43hangePassword\x12\x16.ChangePasswordRequest\x1a\x0e.EmptyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth.auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTYRESPONSE']._serialized_start=25
  _globals['_EMPTYRESPONSE']._serialized_end=40
  _globals['_VERIFYJWTREQUEST']._serialized_start=42
  _globals['_VERIFYJWTREQUEST']._serialized_end=75
  _globals['_LOGINREQUEST']._serialized_start=77
  _globals['_LOGINREQUEST']._serialized_end=124
  _globals['_LOGINRESPONSE']._serialized_start=126
  _globals['_LOGINRESPONSE']._serialized_end=156
  _globals['_REGISTRATIONREQUEST']._serialized_start=158
  _globals['_REGISTRATIONREQUEST']._serialized_end=265
  _globals['_REGISTRATIONRESPONSE']._serialized_start=267
  _globals['_REGISTRATIONRESPONSE']._serialized_end=304
  _globals['_FORGOTPASSWORDREQUEST']._serialized_start=306
  _globals['_FORGOTPASSWORDREQUEST']._serialized_end=344
  _globals['_CHANGEPASSWORDREQUEST']._serialized_start=346
  _globals['_CHANGEPASSWORDREQUEST']._serialized_end=428
  _globals['_AUTHENTICATION']._serialized_start=431
  _globals['_AUTHENTICATION']._serialized_end=712
# @@protoc_insertion_point(module_scope)
