from dotenv import load_dotenv
import os


DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_USER = os.getenv("DB_USER")
DB_DRIVER = os.getenv("DB_DRIVER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

IMAGE_DB_NAME_1 = os.getenv("IMAGE_DB_NAME_1")
IMAGE_DB_1 = (
    f"{DB_DRIVER}://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{IMAGE_DB_NAME_1}"
)

IMAGE_DB_NAME_2 = os.getenv("IMAGE_DB_NAME_2")
IMAGE_DB_2 = (
    f"{DB_DRIVER}://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{IMAGE_DB_NAME_2}"
)

IMAGE_DB_NAME_3 = os.getenv("IMAGE_DB_NAME_3")
IMAGE_DB_3 = (
    f"{DB_DRIVER}://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{IMAGE_DB_NAME_3}"
)

IMAGE_DB_NAME_4 = os.getenv("IMAGE_DB_NAME_4")
IMAGE_DB_4 = (
    f"{DB_DRIVER}://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{IMAGE_DB_NAME_4}"
)

AUTH_SERVICE = os.getenv("AUTH_SERVICE")

REDIS_SERVICE_HOST = os.getenv("REDIS_SERVICE_HOST")
REDIS_SERVICE_PORT = os.getenv("REDIS_SERVICE_PORT")

STORE_SERVICE = os.getenv("STORE_SERVICE")
STORE_SERVICE_VERSION = os.getenv("STORE_SERVICE_VERSION")
