# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.auth import auth_pb2 as proto_dot_auth_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/auth/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AuthenticationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/Authentication/Login',
                request_serializer=proto_dot_auth_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.VerifyJWT = channel.unary_unary(
                '/Authentication/VerifyJWT',
                request_serializer=proto_dot_auth_dot_auth__pb2.VerifyJWTRequest.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.Registration = channel.unary_unary(
                '/Authentication/Registration',
                request_serializer=proto_dot_auth_dot_auth__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.ForgotPassword = channel.unary_unary(
                '/Authentication/ForgotPassword',
                request_serializer=proto_dot_auth_dot_auth__pb2.ForgotPasswordRequest.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/Authentication/ChangePassword',
                request_serializer=proto_dot_auth_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.EmptyResponse.FromString,
                _registered_method=True)


class AuthenticationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyJWT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'VerifyJWT': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyJWT,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.VerifyJWTRequest.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.EmptyResponse.SerializeToString,
            ),
            'Registration': grpc.unary_unary_rpc_method_handler(
                    servicer.Registration,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.RegistrationRequest.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.RegistrationResponse.SerializeToString,
            ),
            'ForgotPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgotPassword,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.ForgotPasswordRequest.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.EmptyResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.ChangePasswordRequest.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Authentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authentication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/Login',
            proto_dot_auth_dot_auth__pb2.LoginRequest.SerializeToString,
            proto_dot_auth_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyJWT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/VerifyJWT',
            proto_dot_auth_dot_auth__pb2.VerifyJWTRequest.SerializeToString,
            proto_dot_auth_dot_auth__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Registration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/Registration',
            proto_dot_auth_dot_auth__pb2.RegistrationRequest.SerializeToString,
            proto_dot_auth_dot_auth__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgotPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/ForgotPassword',
            proto_dot_auth_dot_auth__pb2.ForgotPasswordRequest.SerializeToString,
            proto_dot_auth_dot_auth__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/ChangePassword',
            proto_dot_auth_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
            proto_dot_auth_dot_auth__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
